---
# For Rust builds possible target optimized CPUs are ["znver3", "znver4"]

# NODES
- repository: "babylon"
  project_name: "babylon"
  architecture: "x86_64"
  binaries:
    - "babylond"
  builder: "go"
  builder_version: "1.23.9"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "composable-cosmos"
  automatic_builds: false
  run_docker_build: true
  project_name: "picasso"
  architecture: "x86_64"
  binaries:
    - "picad"
  docker_binaries:
    - "picad"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "dymension"
  project_name: "dymension"
  architecture: "x86_64"
  binaries:
    - "dymd"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "node"
  project_name: "zeta"
  architecture: "x86_64"
  run_docker_build: true
  binaries:
    - "zetacored"
    - "zetaclientd"
    - "zetaclientd-supervisor"
  docker_binaries:
    - "zetacored"
    - "zetaclientd"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: true
  purpose: "node"

- repository: "haqq"
  project_name: "haqq"
  architecture: "x86_64"
  binaries:
    - "haqqd"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "grandine"
  project_name: "grandine"
  architecture: "x86_64"
  binaries:
    - "grandine"
  builder: "rust"
  builder_version: "1.78"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "ssc"
  project_name: "saga"
  architecture: "x86_64"
  binaries:
    - "sscd"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "lighthouse"
  project_name: "lighthouse"
  architecture: "x86_64"
  binaries:
    - "lighthouse"
  builder: "rust"
  builder_version: "1.78"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "jito-solana"
  project_name: "jito"
  architecture: "x86_64"
  binaries:
    - "agave-validator"
  builder: "rust"
  builder_version: "1.76"
  cpu: "znver4"
  patches: false
  purpose: "node"

- repository: "solana"
  project_name: "solana"
  architecture: "x86_64"
  binaries:
    - "solana-validator"
    - "solana-watchtower"
    - "solana"
    - "solana-ledger-tool"
    - "solana-gossip"
    - "solana-genesis"
    - "solana-keygen"
  builder: "rust"
  builder_version: "1.75"
  cpu: "znver3"
  patches: false
  purpose: "node"

- repository: "agave"
  project_name: "agave"
  architecture: "x86_64"
  binaries:
    - "agave-validator"
    - "agave-watchtower"
    - "agave-ledger-tool"
    - "solana"
    - "solana-gossip"
    - "solana-genesis"
    - "solana-keygen"
  builder: "rust"
  builder_version: "1.75"
  cpu: "znver3"
  patches: false
  purpose: "node"

- repository: "sui"
  project_name: "sui"
  architecture: "x86_64"
  binaries:
    - "sui"
    - "sui-node"
    - "sui-tool"
    - "sui-bridge"
    - "sui-bridge-cli"
  builder: "rust"
  builder_version: "1.75"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "bsp-agent"
  project_name: "bsp-agent"
  architecture: "x86_64"
  binaries:
    - "bspagent"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "bsp-geth"
  project_name: "bsp-geth"
  architecture: "x86_64"
  binaries:
    - "geth"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "celestia-app"
  project_name: "celestia"
  architecture: "x86_64"
  binaries:
    - "celestia-appd"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "celestia-node"
  project_name: "celestia-node"
  architecture: "x86_64"
  binaries:
    - "celestia"
  builder: "go"
  builder_version: "1.23.1"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "linera-protocol"
  project_name: "linera"
  architecture: "x86_64"
  run_docker_build: true
  binaries:
    - "linera"
    - "linera-db"
    - "linera-proxy"
    - "linera-schema-export"
    - "linera-server"
  docker_binaries:
    - "linera"
    - "linera-db"
    - "linera-server"
    - "linera-proxy"
  builder: "rust"
  builder_version: "1.75"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "pathfinder"
  project_name: "pathfinder"
  architecture: "x86_64"
  binaries:
    - "pathfinder"
  builder: "rust"
  builder_version: "1.80"
  cpu: "x86_64"
  patches: false
  purpose: "node"

- repository: "namada"
  project_name: "namada"
  architecture: "x86_64"
  binaries:
    - "namada"
  builder: "rust"
  builder_version: "1.80"
  cpu: "x86_64"
  patches: false
  purpose: "node"

- repository: "cosmos-sdk"
  project_name: "symbiotic"
  architecture: "x86_64"
  binaries:
    - "symd"
  builder: "go"
  builder_version: "1.23.1"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "gonative"
  project_name: "native"
  architecture: "x86_64"
  binaries:
    - "gonative"
  builder: "go"
  builder_version: "1.23.4"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "imuachain"
  project_name: "exocore"
  architecture: "x86_64"
  binaries:
    - "imuad"
  builder: "go"
  builder_version: "1.21.12"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "Passage3D"
  project_name: "passage"
  architecture: "x86_64"
  binaries:
    - "passage"
  builder: "go"
  builder_version: "1.20"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "persistenceCore"
  project_name: "persistenceCore"
  architecture: "x86_64"
  binaries:
    - "persistenceCore"
  builder: "go"
  builder_version: "1.23.6"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "chain-main"
  project_name: "cronos"
  architecture: "x86_64"
  binaries:
    - "chain-maind"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "omniflixhub"
  project_name: "omniflixhub"
  architecture: "x86_64"
  binaries:
    - "omniflixhubd"
  builder: "go"
  builder_version: "1.24.3"
  cpu: "generic"
  patches: false
  purpose: "node"

- repository: "juno"
  project_name: "juno"
  architecture: "x86_64"
  binaries:
    - "juno"
  builder: "go"
  builder_version: "1.24.3"
  cpu: "generic"
  patches: false
  purpose: "node"
  runner: "ubuntu-latest"

# TOOLS
- repository: "tmkms"
  project_name: "tmkms"
  architecture: "x86_64"
  binaries:
    - "tmkms"
  builder: "rust"
  builder_version: "1.75"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "tenderduty"
  project_name: "tenderduty"
  architecture: "x86_64"
  binaries:
    - "tenderduty"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "ipfs-pinner"
  project_name: "ipfs-pinner"
  architecture: "x86_64"
  binaries:
    - "server"
  builder: "go"
  builder_version: "1.22.8"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "ewm-das"
  project_name: "ewm-das"
  architecture: "x86_64"
  binaries:
    - "pinner"
    - "pinner-cli"
  builder: "go"
  builder_version: "1.24.1"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "composable"
  project_name: "picasso-price-feed"
  architecture: "x86_64"
  binaries:
    - "price-feed"
  builder: "rust"
  builder_version: "1.70"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "btc-staker"
  project_name: "babylon-btc-staker"
  architecture: "x86_64"
  binaries:
    - "stakerd"
    - "stakercli"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "finality-provider"
  project_name: "babylon-fp"
  architecture: "x86_64"
  run_docker_build: true
  binaries:
    - "eotsd"
    - "fpd"
  docker_binaries:
    - "eotsd"
    - "fpd"
  builder: "go"
  builder_version: "1.23.4"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "jito-relayer"
  project_name: "jito-relayer"
  architecture: "x86_64"
  binaries:
    - "jito-transaction-relayer"
  builder: "rust"
  builder_version: "1.76"
  cpu: "x86-64"
  patches: false
  purpose: "tool"

- repository: "horcrux-proxy"
  project_name: "horcrux-proxy"
  architecture: "x86_64"
  binaries:
    - "horcrux-proxy"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: false
  purpose: "tool"

- repository: "gaia"
  project_name: "cosmoshub"
  architecture: "x86_64"
  binaries:
    - "gaiad"
  builder: "go"
  builder_version: "1.22.4"
  cpu: "generic"
  patches: false
  purpose: "node"

# Docker images

- repository: "bouncebit"
  project_name: "bouncebit"
  architecture: "x86_64"
  run_docker_build: true
  run_build: false
