---
- repository: "composable-cosmos"
  name: "centauri"
  architectures:
    - "x86_64"
  binaries:
    - "centaurid"
  builder: "go"
  builder_version: "1.21.5"
  cpu: "generic"
  dockerfile: "centauri"
  dockerfile_binary: "centaurid"
  patches: false
  purpose: "testing"

- repository: "sui"
  name: "sui"
  architectures:
    - "x86_64"
  binaries:
    - "sui"
    - "suinode"
  builder: "rust"
  builder_version: "1.75"
  cpu: "generic"
  dockerfile: "sui-dockerfile"
  dockerfile_binary: "suinode"
  patches: false
  purpose: "testing"

- repository: "jito"
  name: "jito"
  architectures:
    - "x86_64"
  binaries:
    - "solana-validator"
  builder: "rust"
  builder_version: "1.76"
  cpu: "generic"
  dockerfile: "jito-solana"
  dockerfile_binary: "jito-solana"
  patches: false
  purpose: "testing"
