name: "Build Binary"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the version"
        required: true
        default: "v0.0.1"
      repository:
        description: "Specify the repository"
        required: true
        default: "jito-solana"
      organization:
        description: "Specify the organization"
        required: true
        default: "jito-foundation"
      protocol:
        description: "Specify the protocol"
        required: true
        default: "jito"
  pull_request:
    branches:
      - "master"

env:
  version: "${{ inputs.version || 'v1.0.0' }}"
  repository: "${{ inputs.repository || 'jito-solana' }}"
  organization: "${{ inputs.organization || 'jito-foundation' }}"
  protocol: "${{ inputs.protocol || 'jito' }}"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest-l"
    steps:
      - id: "setup-go"
        name: "Setup Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.20"

      - id: "setup-dependencies"
        name: "Install required system packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential curl git musl-dev

      - id: "clone-pipeline"
        name: "Clone pipeline"
        uses: "actions/checkout@v4"
        with:
          path: "pipeline"

      - id: "clone"
        name: "Clone Protocol source"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ env.organization }}/${{ env.repository }}"
          fetch-tags: true
          path: "${{ env.protocol }}"
          ref: "refs/tags/${{ env.version }}"

      - name: "Run protocol-specific build script"
        run: |
          protocol_script=".github/scripts/${{ inputs.repository }}-build.sh"

          if [ -f "$protocol_script" ]; then
            export BINARY_VERSION="${{ inputs.version }}"
            export BINARY_PROTOCOL"${{ inputs.protocol }}"
            bash "$protocol_script"
          else
            echo "Error: Invalid repository specified or missing build script '$protocol_script'"
            exit 1
          fi

      - id: "upload-artifact"
        name: "Save binary to workspace"
        uses: "actions/upload-artifact@v3"
        with:
          name: "${{ env.protocol }}-validator"
          path: "./${{ env.protocol }}/target/release/${{ env.protocol }}-validator-${{ env.version }}"
          if-no-files-found: "error"
          retention-days: 1