name: "Build Binary"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the version"
        required: true
        default: "v1.18.22"
      repository:
        description: "Specify the repository"
        required: true
        default: "composable-cosmos"
      organization:
        description: "Specify the organization"
        required: true
        default: "ComposableFi"
      protocol:
        description: "Specify the protocol"
        required: true
        default: "centauri"
      binaryname:
        description: "Specify the binary name"
        required: true
        default: "centaurid"
      cpu:
        description: "Specify the cpu"
        required: true
        default: "generic"
      arch:
        description: "Specify the arch"
        required: true
        default: "x86_64"
      purpose:
        description: "Specify the purpose"
        required: true
        default: "node"
      patches:
        description: "Specify the patch condition"
        required: true
        default: "false"
  pull_request:
    branches:
      - "master"

env:
  version: "${{ inputs.version || 'testnet-v1.19.0' }}"
  repository: "${{ inputs.repository || 'sui' }}"
  organization: "${{ inputs.organization || 'MystenLabs' }}"
  protocol: "${{ inputs.protocol || 'sui' }}"
  binaryname: "${{ inputs.binaryname || 'sui' }}"
  cloudflare_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
  cloudflare_secret: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  cloudflare_account: ${{ secrets.cloudflare_account }}
  cpu: "${{ inputs.cpu || 'generic' }}"
  arch: "${{ inputs.arch || 'x86_64' }}"
  purpose: "${{ inputs.purpose || 'test' }}"
  patches: "${{ inputs.patches || 'false' }}"


jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest-l"
    steps:
      - uses: actions/checkout@v2

      - name: Use Deno Version 1.41.0
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.41.0

      - id: "setup-dependencies"
        name: "Install required system packages"
        run: |
          sudo add-apt-repository -y ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential curl git musl-dev jq yq
          chmod +x ${GITHUB_WORKSPACE}/dependencies/${{env.protocol}}-dependencies.sh
          bash ${GITHUB_WORKSPACE}/dependencies/${{env.protocol}}-dependencies.sh

      - id: "setup-builder"
        name: "Setup Builder"
        run: |
          chmod +x ${GITHUB_WORKSPACE}/scripts/setup-builder.sh
          export BINARY_PROTOCOL="${{ env.protocol }}"
          sh ${GITHUB_WORKSPACE}/scripts/setup-builder.sh

      - id: "clone-pipeline"
        name: "Clone pipeline"
        uses: "actions/checkout@v4"
        with:
          path: "pipeline"

      - id: "clone"
        name: "Clone Protocol source"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ env.organization }}/${{ env.repository }}"
          fetch-tags: true
          path: "${{ env.protocol }}"
          ref: "refs/tags/${{ env.version }}"
          submodules: true

      - id: "apply-patches"
        name: "Apply patches"
        if: ${{ env.patches == 'true' }}
        run: |
          set -euo pipefail
          shopt -s nullglob
          cd "${GITHUB_WORKSPACE}/${{ env.protocol }}"
          git am --3way "${GITHUB_WORKSPACE}/pipeline/patches"/*.patch

      - name: "Run protocol-specific build script"
        run: |
          protocol_script="${GITHUB_WORKSPACE}/scripts/${{ env.protocol }}-build.sh"
          chmod +x ${GITHUB_WORKSPACE}/scripts/${{ env.protocol }}-build.sh
          if [ -f "$protocol_script" ]; then
            export BINARY_ARCH="${{ env.arch }}"
            export BINARY_CPU="${{ env.cpu }}"
            export BINARY_VERSION="${{ env.version }}"
            export BINARY_PROTOCOL="${{ env.protocol }}"
            export BINARY_NAME="${{ env.binaryname }}"
            bash "$protocol_script"
          else
            echo "Error: Invalid repository specified or missing build script '$protocol_script'"
            exit 1
          fi

      - id: "show-env"
        name: "Show files"
        run: |
          set -x
          ls -la

      - id: "generate-paths"
        name: "Generate binaries paths"
        run: |
          export BINARY_ARCH="${{ env.arch }}"
          export BINARY_CPU="${{ env.cpu }}"
          export BINARY_VERSION="${{ env.version }}"
          export BINARY_PROTOCOL="${{ env.protocol }}"
          export BINARY_NAME="${{ env.binaryname }}"
          deno run --allow-read --allow-env --allow-write set-binaries.ts

      - id: "generate-var"
        name: "Generate binaries github variable"
        run: |
          echo $ENVVAR_BINARIES

      - id: "upload-artifacts"
        name: "Save binary to workspace"
        uses: "actions/upload-artifact@v3"
        with:
          name: "binaries"
          path: "${{env.ENVVAR_BINARIES}}"
          if-no-files-found: "error"
          retention-days: 1

  upload:
    name: "Upload"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - id: "download-artifacts"
        name: "Download binaries from workspace"
        uses: "actions/download-artifact@v3"
        with:
          name: "binaries"
          path: "binaries"

      - id: "setup-rclone"
        name: "Set up rclone CLI"
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - id: "upload-binary"
        name: Upload binary to R2 bucket
        run: |
          set -euo pipefail
          export RCLONE_CONFIG_R2_TYPE=s3
          export RCLONE_CONFIG_R2_ACCESS_KEY_ID=${{env.cloudflare_key_id}}
          export RCLONE_CONFIG_R2_SECRET_ACCESS_KEY=${{env.cloudflare_secret}}
          export RCLONE_CONFIG_R2_REGION=auto
          export RCLONE_CONFIG_R2_PROVIDER=Cloudflare
          export RCLONE_CONFIG_R2_ENDPOINT=https://41b3fe4c8001defd8adf7a0ceafb504d.r2.cloudflarestorage.com
          export RCLONE_CONFIG_R2_ACL=private
          export RCLONE_CONFIG_R2_NO_CHECK_BUCKET=true

          for file in binaries/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              rclone copy "$file" "r2:binaries/${{env.purpose}}/${{env.protocol}}/${{env.version}}/${filename}"
            fi
          done

  publish:
    name: "Publish"
    needs: "build"
    runs-on: "ubuntu-latest"
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    steps:
      - id: "download-artifact"
        name: "Download binary from workspace"
        uses: "actions/download-artifact@v3"
        with:
          name: "${{ env.binaryname }}-${{env.cpu}}-${{env.arch}}"
          path: "binaries"

      - id: "publish"
        name: "Publish Github release"
        uses: "softprops/action-gh-release@v1"
        with:
          body: |
            For changes, see here: https://github.com/${{ env.organization }}/${{env.repository}}/releases/tag/${{ env.version }}
          files: |
            ${{ env.binaryname }}-${{ env.version }}
          tag_name: "${{ env.version }}"
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
